device_map = {'model.decoder.embed_tokens': 0,
 'model.decoder.embed_positions': 0,
 'model.decoder.layers.0': 0,
 'model.decoder.layers.1': 0,
 'model.decoder.layers.2': 0,
 'model.decoder.layers.3': 0,
 'model.decoder.layers.4': 0,
 'model.decoder.layers.5': 0,
 'model.decoder.layers.6': 0,
 'model.decoder.layers.7': 0,
 'model.decoder.layers.8': 0,
 'model.decoder.layers.9': 0,
 'model.decoder.layers.10': 0,
 'model.decoder.layers.11': 0,
 'model.decoder.layers.12': 0,
 'model.decoder.layers.13': 0,
 'model.decoder.layers.14': 0,
 'model.decoder.layers.15': 0,
 'model.decoder.layers.16': 0,
 'model.decoder.layers.17': 0,
 'model.decoder.layers.18': 0,
 'model.decoder.layers.19': 0,
 'model.decoder.layers.20': 0,
 'model.decoder.layers.21': 0,
 'model.decoder.layers.22': 0,
 'model.decoder.layers.23': 0,
 'model.decoder.layers.24': 0,
 'model.decoder.layers.25': 1,
 'model.decoder.layers.26': 1,
 'model.decoder.layers.27': 1,
 'model.decoder.layers.28': 1,
 'model.decoder.layers.29': 1,
 'model.decoder.layers.30': 1,
 'model.decoder.layers.31': 1,
 'model.decoder.layers.32': 1,
 'model.decoder.layers.33': 1,
 'model.decoder.layers.34': 1,
 'model.decoder.layers.35': 1,
 'model.decoder.layers.36': 1,
 'model.decoder.layers.37': 1,
 'model.decoder.layers.38': 1,
 'model.decoder.layers.39': 1,
 'model.decoder.layers.40': 1,
 'model.decoder.layers.41': 1,
 'model.decoder.layers.42': 1,
 'model.decoder.layers.43': 1,
 'model.decoder.layers.44': 1,
 'model.decoder.layers.45': 1,
 'model.decoder.layers.46': 1,
 'model.decoder.layers.47': 1,
 'model.decoder.layers.48': 1,
 'model.decoder.final_layer_norm': 1,
 'lm_head': 1}

data_dir = ''
hf_datasets_cache = ''
output_dir = ''

